owner: tanssinet
repo: up

sites:
  - name: tanssi.net
    url: https://tanssi.net

status-website:
  cname: status.tanssi.io
  logoUrl: https://status.tanssi.io/tanssi_net_logo_white_on_blue_cropped.png
  name: tanssi.net
  introTitle: tanssi.netin valvonta
  introMessage: Palveluiden saatavuus
  navbar:
    - title: Tila
      href: /
    - title: Tiketit
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://status.tanssi.io/theme.css
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
      - name: "robots"
        content: "noindex"
