# Change these first
owner: tanssinet # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: tanssi.net
    url: https://tanssi.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tanssi.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: tanssi.net
  introTitle: tanssi.netin valvonta
  introMessage: Palveluiden saatavuus
  navbar:
    - title: Tila
      href: /
    - title: Tiketit
      href: https://github.com/$OWNER/$REPO
