owner: tanssinet
repo: up

sites:
  - name: Kalenteri
    url: https://tanssi.net/cal/events/2024/4/16/
  - name: Esiintyjät
    url: https://tanssi.net/cal/performers/
  - name: Tapahtumapaikat
    url: https://tanssi.net/cal/venues/

status-website:
  cname: status.tanssi.io
  logoUrl: https://status.tanssi.io/tanssi_net_logo_white_on_blue_cropped.png
  name: ""
  introTitle: tanssi.net | Palveluiden saatavuus
  introMessage: Alla näet palveluiden tilan. Jos järjestelmät ovat pysyvästi alhaalla, saat lisätietoja sivulta Tiketit
  navbar:
    - title: Tila
      href: /
    - title: Tiketit
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://status.tanssi.io/theme.css
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
      - name: "robots"
        content: "noindex"
  css: "nav { color: #fefefe !important; } article { color: #fefefe !important; } main { color: #212529 !important; }"
